name: Get Node and install deps
description: Sets the Node.js version and initializes core dependencies
inputs:
  node-version:
    description: 'Number of Octocats'
    required: false
    default: ''
  
runs:
  using: composite
  steps:
    - name: Log
      run: |
        echo "github repository: ${{ github.repository }}"
      shell: bash
    - uses: actions/checkout@v4
    - name: Log
      run: |
        echo "github repository: ${{ github.repository }}"
      shell: bash
    - name: Use Node Version from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      shell: bash