name: Publish Package on NPM
on:
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Istantiate Node
        uses: iconsauce/.github/setup-node
      - name: Publish Package
        uses: iconsauce/.github/publish-npm
        with:
          token: ${{ secrets.NPM_TOKEN }}
