name: Publish Package on NPM
on:
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          echo "github repository: ${{ github.repository }}"
        shell: bash
      - name: Istantiate Node
        uses: ./github/actions/setup-node
      - name: Publish Package
        uses: ./.github/actions/publish-npm
        with:
          token: ${{ secrets.NPM_TOKEN }}
