name: Publish Package on NPM
on:
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Log
        run: |
          echo "github repository: ${{ github.repository }}"
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4
      - name: Istantiate Node
        uses: iconsauce/.github/.github/actions/setup-node@main
      - name: Publish Package
        uses: iconsauce/.github/.github/actions/publish-npm@main
        with:
          token: ${{ secrets.NPM_TOKEN }}
